### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Shock95** [Rspuds/AreaEffects#2]
Could not pass event 'pocketmine\event\player\PlayerMoveEvent' to 'AreaEffects v1.1.3': Argument 1 passed to pocketmine\utils\Config::setDefaults() must be of the type array, null given, called in phar://C:/Users/Tajwar/Corel/PocketMine-MP/ImagicalMine.phar/src/pocketmine/plugin/PluginBase.php on line 241 and defined on AreaEffects\Main

InvalidArgumentException: "Argument 1 passed to pocketmine\utils\Config::setDefaults() must be of the type array, null given, called in phar://C:/Users/Tajwar/Corel/PocketMine-MP/ImagicalMine.phar/src/pocketmine/plugin/PluginBase.php on line 241 and defined" (E_RECOVERABLE_ERROR) in "/src/pocketmine/utils/Config" at line 395

**Comment by XShockinFireX** [comment]
plz fix

**Comment by Shock95** [comment]
@thebigsmileXD can you fix this?

**Comment by inxomnyaa** [comment]
Sure, forgot about this..

**Comment by Shock95** [comment]
k
